// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTest3.Data;

#nullable disable

namespace ProjectTest3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250323161820_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectTest3.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ABC@example.com",
                            GenderId = 1,
                            Name = "ABC",
                            PhoneNumber = 1234567890L,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "DEF@example.com",
                            GenderId = 2,
                            Name = "DEF",
                            PhoneNumber = 2345678901L,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "HIJ@example.com",
                            GenderId = 3,
                            Name = "HIJ",
                            PhoneNumber = 3456789012L,
                            PositionId = 3
                        });
                });

            modelBuilder.Entity("ProjectTest3.Models.EmployeeLanguage", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("EmployeeLanguages");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            LanguageId = 1
                        },
                        new
                        {
                            EmployeeId = 1,
                            LanguageId = 4
                        },
                        new
                        {
                            EmployeeId = 1,
                            LanguageId = 5
                        },
                        new
                        {
                            EmployeeId = 2,
                            LanguageId = 4
                        },
                        new
                        {
                            EmployeeId = 2,
                            LanguageId = 3
                        },
                        new
                        {
                            EmployeeId = 3,
                            LanguageId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            LanguageId = 1
                        });
                });

            modelBuilder.Entity("ProjectTest3.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ProjectTest3.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = 7,
                            Name = "PHP"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Go"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Swift"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kotlin"
                        });
                });

            modelBuilder.Entity("ProjectTest3.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Designer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tester"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Analyst"
                        },
                        new
                        {
                            Id = 6,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("ProjectTest3.Models.Employee", b =>
                {
                    b.HasOne("ProjectTest3.Models.Gender", "Gender")
                        .WithMany("Employees")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTest3.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ProjectTest3.Models.EmployeeLanguage", b =>
                {
                    b.HasOne("ProjectTest3.Models.Employee", "Employee")
                        .WithMany("EmployeeLanguages")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectTest3.Models.Language", "Language")
                        .WithMany("EmployeeLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ProjectTest3.Models.Employee", b =>
                {
                    b.Navigation("EmployeeLanguages");
                });

            modelBuilder.Entity("ProjectTest3.Models.Gender", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ProjectTest3.Models.Language", b =>
                {
                    b.Navigation("EmployeeLanguages");
                });

            modelBuilder.Entity("ProjectTest3.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
